# ApiCalling

In [2]:
import pandas as pd
import requests

In [2]:
url = "https://api.coingecko.com/api/v3/coins/markets"

In [4]:
parameters = {
    "vs_currency": "usd",          # give prices in USD
    "order": "market_cap_desc",    # sort by market cap (biggest first)
    "per_page": 100,               # give 100 coins
    "page": 1,                     # first page
    "sparkline": False   
}

In [5]:
response = requests.get(url=url , params=parameters)

In [6]:
response.status_code

200

In [7]:
response.url

'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=False'

In [9]:
data = response.json()

In [10]:
data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 63767,
  'market_cap': 1272574839213,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 1272574839213,
  'total_volume': 59388208934,
  'high_24h': 67327,
  'low_24h': 61557,
  'price_change_24h': -3297.2591317158003,
  'price_change_percentage_24h': -4.91655,
  'market_cap_change_24h': -72981827510.177,
  'market_cap_change_percentage_24h': -5.42391,
  'circulating_supply': 20038434.0,
  'total_supply': 20038434.0,
  'max_supply': 21000000.0,
  'ath': 126080,
  'ath_change_percentage': -49.42314,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 67.81,
  'atl_change_percentage': 93939.50483,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:30.635Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 1779.85,
  'market_cap': 214167886224,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 214167886224,
  'total_volume': 26250900448,
  'high_24h': 1886.55,
  'low_24h': 1734.05,
  'price_change_24h': -94.28603485583312,
  'price_change_percentage_24h': -5.03091,
  'market_cap_change_24h': -12188410575.233063,
  'market_cap_change_percentage_24h': -5.38461,
  'circulating_supply': 120684919.7706288,
  'total_supply': 120684919.7706288,
  'max_supply': None,
  'ath': 4946.05,
  'ath_change_percentage': -64.01473,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 0.432979,
  'atl_change_percentage': 410970.57901,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 36.325361250625974,
   'currency': 'btc',
   'percentage': 3632.5361250625974},
  'last_updated': '2026-06-04T08:05:30.643Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 0.998961,
  'market_cap': 187340958430,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 192802397763,
  'total_volume': 340399986415,
  'high_24h': 0.999068,
  'low_24h': 0.998398,
  'price_change_24h': 0.00031909,
  'price_change_percentage_24h': 0.03195,
  'market_cap_change_24h': -504525298.64282227,
  'market_cap_change_percentage_24h': -0.26859,
  'circulating_supply': 187529700104.6057,
  'total_supply': 192996641710.8862,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.49614,
  'ath_date': '2018-07-24T00:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.48933,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:27.297Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 601.78,
  'market_cap': 80845491220,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 80845491220,
  'total_volume': 1968995512,
  'high_24h': 644.83,
  'low_24h': 595.1,
  'price_change_24h': -40.95071719972361,
  'price_change_percentage_24h': -6.3714,
  'market_cap_change_24h': -5836289264.628479,
  'market_cap_change_percentage_24h': -6.73301,
  'circulating_supply': 134784329.17,
  'total_supply': 134784329.17,
  'max_supply': 200000000.0,
  'ath': 1369.99,
  'ath_change_percentage': -56.07442,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1511229.72431,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:30.443Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 0.999541,
  'market_cap': 75958066511,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 75960481767,
  'total_volume': 21684670704,
  'high_24h': 1.0,
  'low_24h': 0.999255,
  'price_change_24h': -0.000145916963138593,
  'price_change_percentage_24h': -0.0146,
  'market_cap_change_24h': 44081849,
  'market_cap_change_percentage_24h': 0.05807,
  'circulating_supply': 75991668235.67851,
  'total_supply': 75994084559.67462,
  'max_supply': None,
  'ath': 1.043,
  'ath_change_percentage': -4.20681,
  'ath_date': '2018-11-15T00:00:00.000Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.89185,
  'atl_date': '2023-03-11T08:02:13.981Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:27.519Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 1.17,
  'market_cap': 72237192808,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 116536535615,
  'total_volume': 2916108328,
  'high_24h': 1.24,
  'low_24h': 1.14,
  'price_change_24h': -0.07513450971319635,
  'price_change_percentage_24h': -6.04596,
  'market_cap_change_24h': -4630123743.57605,
  'market_cap_change_percentage_24h': -6.02353,
  'circulating_supply': 61977843307.0,
  'total_supply': 99985656462.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -67.97949,
  'ath_date': '2025-07-18T03:40:53.808Z',
  'atl': 0.00268621,
  'atl_change_percentage': 43366.08834,
  'atl_date': '2014-05-22T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:27.150Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 69.22,
  'market_cap': 39967628994,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 43368123343,
  'total_volume': 4862498050,
  'high_24h': 75.52,
  'low_24h': 67.35,
  'price_change_24h': -5.956991485567713,
  'price_change_percentage_24h': -7.92345,
  'market_cap_change_24h': -3518872856.6227036,
  'market_cap_change_percentage_24h': -8.09187,
  'circulating_supply': 578441924.6339062,
  'total_supply': 627656465.1372303,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -76.3989,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 0.500801,
  'atl_change_percentage': 13722.82167,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:27.034Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 0.330957,
  'market_cap': 31386599454,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 31386970280,
  'total_volume': 682211365,
  'high_24h': 0.335218,
  'low_24h': 0.329622,
  'price_change_24h': -0.00228256127898685,
  'price_change_percentage_24h': -0.68496,
  'market_cap_change_24h': -209853730.2671852,
  'market_cap_change_percentage_24h': -0.66417,
  'circulating_supply': 94817116410.57059,
  'total_supply': 94818236654.81897,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -23.26323,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.00180434,
  'atl_change_percentage': 18242.24355,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 173.1877563868875,
   'currency': 'usd',
   'percentage': 17318.77563868875},
  'last_updated': '2026-06-04T08:05:23.435Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 1.001,
  'market_cap': 18455449424,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 18455449424,
  'total_volume': 750623058,
  'high_24h': 1.035,
  'low_24h': 1.001,
  'price_change_24h': -0.034422299999999906,
  'price_change_percentage_24h': -3.32499,
  'market_cap_change_24h': -572187924.8873253,
  'market_cap_change_percentage_24h': -3.00714,
  'circulating_supply': 18440000391.817,
  'total_supply': 18440000391.817,
  'max_supply': None,
  'ath': 1.049,
  'ath_change_percentage': -4.60203,
  'ath_date': '2026-03-09T17:00:25.937Z',
  'atl': 0.155357,
  'atl_change_percentage': 544.21969,
  'atl_date': '2025-10-31T14:27:24.456Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:27.458Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 68.37,
  'market_cap': 15091062761,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 64809516119,
  'total_volume': 1638935636,
  'high_24h': 75.21,
  'low_24h': 67.85,
  'price_change_24h': -4.650889310350394,
  'price_change_percentage_24h': -6.36897,
  'market_cap_change_24h': -1171904895.8583984,
  'market_cap_change_percentage_24h': -7.20597,
  'circulating_supply': 222445714.0741414,
  'total_supply': 955307079.4341414,
  'max_supply': 1000000000.0,
  'ath': 75.48,
  'ath_change_percentage': -9.41534,
  'ath_date': '2026-06-02T03:26:51.695Z',
  'atl': 3.81,
  'atl_change_percentage': 1695.16771,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:26.432Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 0.088883,
  'market_cap': 13713981583,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 15108461674,
  'total_volume': 1280767075,
  'high_24h': 0.094303,
  'low_24h': 0.086974,
  'price_change_24h': -0.005000763369079286,
  'price_change_percentage_24h': -5.32657,
  'market_cap_change_24h': -809155831.9848328,
  'market_cap_change_percentage_24h': -5.57149,
  'circulating_supply': 154517786383.7052,
  'total_supply': 170229633126.5791,
  'max_supply': None,
  'ath': 0.731578,
  'ath_change_percentage': -87.85057,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 8.69e-05,
  'atl_change_percentage': 102177.03086,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:26.215Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 0.999605,
  'market_cap': 10964333962,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 10964333962,
  'total_volume': 65638516,
  'high_24h': 1.0,
  'low_24h': 0.998888,
  'price_change_24h': -6.4668676490132e-05,
  'price_change_percentage_24h': -0.00647,
  'market_cap_change_24h': -136758.22751808167,
  'market_cap_change_percentage_24h': -0.00125,
  'circulating_supply': 10968505745.20601,
  'total_supply': 10968505745.20601,
  'max_supply': None,
  'ath': 1.15,
  'ath_change_percentage': -13.23442,
  'ath_date': '2026-04-02T07:21:14.655Z',
  'atl': 0.948265,
  'atl_change_percentage': 5.41528,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:26.493Z'},
 {'id': 'zcash',
  'symbol': 'zec',
  'name': 'Zcash',
  'image': 'https://coin-images.coingecko.com/coins/images/486/large/circle-zcash-color.png?1696501740',
  'current_price': 570.63,
  'market_cap': 9486564259,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 9486564259,
  'total_volume': 1161762233,
  'high_24h': 632.67,
  'low_24h': 570.3,
  'price_change_24h': -47.802916022230306,
  'price_change_percentage_24h': -7.72969,
  'market_cap_change_24h': -850411244.7627449,
  'market_cap_change_percentage_24h': -8.22689,
  'circulating_supply': 16688225.1655448,
  'total_supply': 16688225.1655448,
  'max_supply': 21000000.0,
  'ath': 3191.93,
  'ath_change_percentage': -82.12273,
  'ath_date': '2016-10-29T00:00:00.000Z',
  'atl': 16.08,
  'atl_change_percentage': 3448.66403,
  'atl_date': '2024-07-05T04:22:29.321Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:26.331Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 9.94,
  'market_cap': 9149933646,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 9793719453,
  'total_volume': 589797,
  'high_24h': 10.13,
  'low_24h': 9.91,
  'price_change_24h': -0.14475255942023324,
  'price_change_percentage_24h': -1.43531,
  'market_cap_change_24h': -132861543.29393196,
  'market_cap_change_percentage_24h': -1.43127,
  'circulating_supply': 920475221.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 10.57,
  'ath_change_percentage': -5.87038,
  'ath_date': '2026-05-04T09:45:26.809Z',
  'atl': 0.799859,
  'atl_change_percentage': 1143.86215,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:28.412Z'},
 {'id': 'rain',
  'symbol': 'rain',
  'name': 'Rain',
  'image': 'https://coin-images.coingecko.com/coins/images/69134/large/Rain_logo_1_.png?1762952191',
  'current_price': 0.01394334,
  'market_cap': 8668400937,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 16008310727,
  'total_volume': 43757121,
  'high_24h': 0.01441939,
  'low_24h': 0.01376267,
  'price_change_24h': -6.4612580116702e-05,
  'price_change_percentage_24h': -0.46126,
  'market_cap_change_24h': -59917300.66497803,
  'market_cap_change_percentage_24h': -0.68647,
  'circulating_supply': 622645584959.01,
  'total_supply': 1149866517409.704,
  'max_supply': 1150000000000.0,
  'ath': 0.01478538,
  'ath_change_percentage': -5.80855,
  'ath_date': '2026-05-27T18:55:48.614Z',
  'atl': 0.00222126,
  'atl_change_percentage': 526.96727,
  'atl_date': '2025-09-14T08:56:57.416Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:28.073Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 0.1949,
  'market_cap': 7233692624,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 8759851326,
  'total_volume': 845318010,
  'high_24h': 0.217899,
  'low_24h': 0.189967,
  'price_change_24h': -0.02212537449936708,
  'price_change_percentage_24h': -10.19482,
  'market_cap_change_24h': -819293358.0198908,
  'market_cap_change_percentage_24h': -10.17378,
  'circulating_supply': 37160010595.838,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 3.09,
  'ath_change_percentage': -93.68624,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 0.01925275,
  'atl_change_percentage': 912.3241,
  'atl_date': '2020-03-13T02:22:55.044Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:29.049Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 0.208808,
  'market_cap': 7033424412,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 10434139784,
  'total_volume': 939460079,
  'high_24h': 0.232465,
  'low_24h': 0.199583,
  'price_change_24h': -0.021781893515257222,
  'price_change_percentage_24h': -9.44615,
  'market_cap_change_24h': -738427487.9161406,
  'market_cap_change_percentage_24h': -9.50131,
  'circulating_supply': 33705106073.64661,
  'total_supply': 50001786839.91258,
  'max_supply': None,
  'ath': 0.875563,
  'ath_change_percentage': -76.14869,
  'ath_date': '2018-01-03T00:00:00.000Z',
  'atl': 0.00047612,
  'atl_change_percentage': 43761.15355,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:30.659Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 359.25,
  'market_cap': 6733869395,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 6733869395,
  'total_volume': 169707385,
  'high_24h': 368.38,
  'low_24h': 335.69,
  'price_change_24h': 22.2,
  'price_change_percentage_24h': 6.58615,
  'market_cap_change_24h': 411150056,
  'market_cap_change_percentage_24h': 6.50274,
  'circulating_supply': 18760460.02915472,
  'total_supply': 18760460.02915472,
  'max_supply': None,
  'ath': 797.73,
  'ath_change_percentage': -54.9666,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 0.216177,
  'atl_change_percentage': 166082.19265,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:27.989Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 0.155569,
  'market_cap': 6017048677,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 6017048677,
  'total_volume': 22572862,
  'high_24h': 0.155779,
  'low_24h': 0.150351,
  'price_change_24h': 0.00480339,
  'price_change_percentage_24h': 3.18601,
  'market_cap_change_24h': 181529176,
  'market_cap_change_percentage_24h': 3.11076,
  'circulating_supply': 38710783612.3368,
  'total_supply': 38710783612.3368,
  'max_supply': None,
  'ath': 0.194152,
  'ath_change_percentage': -19.95271,
  'ath_date': '2026-02-03T08:02:08.411Z',
  'atl': 0.059024,
  'atl_change_percentage': 163.30478,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:28.181Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 8.07,
  'market_cap': 5860661968,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 8060324861,
  'total_volume': 489013332,
  'high_24h': 8.59,
  'low_24h': 7.93,
  'price_change_24h': -0.46317946172788815,
  'price_change_percentage_24h': -5.42715,
  'market_cap_change_24h': -344411023.1705284,
  'market_cap_change_percentage_24h': -5.55047,
  'circulating_supply': 727099970.4255477,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 52.7,
  'ath_change_percentage': -84.68338,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 0.148183,
  'atl_change_percentage': 5346.86565,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:28.761Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 46.16,
  'market_cap': 5460594034,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 13580665688,
  'total_volume': 142601862,
  'high_24h': 49.25,
  'low_24h': 45.14,
  'price_change_24h': -2.930000000000007,
  'price_change_percentage_24h': -5.96826,
  'market_cap_change_24h': -348362312.4499998,
  'market_cap_change_percentage_24h': -5.99699,
  'circulating_supply': 118289410.0,
  'total_supply': 294189409.0,
  'max_supply': 400000000.0,
  'ath': 64.11,
  'ath_change_percentage': -27.98932,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 3.06,
  'atl_change_percentage': 1407.75942,
  'atl_date': '2023-02-13T19:01:21.899Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:24.452Z'},
 {'id': 'lab',
  'symbol': 'lab',
  'name': 'LAB',
  'image': 'https://coin-images.coingecko.com/coins/images/70014/large/lab.png?1760352822',
  'current_price': 17.48,
  'market_cap': 5457853289,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 17462736257,
  'total_volume': 64008918,
  'high_24h': 19.65,
  'low_24h': 15.15,
  'price_change_24h': 1.026,
  'price_change_percentage_24h': 6.23868,
  'market_cap_change_24h': 357088086,
  'market_cap_change_percentage_24h': 7.00068,
  'circulating_supply': 312542846.0,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 27.3,
  'ath_change_percentage': -35.99157,
  'ath_date': '2026-06-02T21:05:47.499Z',
  'atl': 0.074235,
  'atl_change_percentage': 23439.94323,
  'atl_date': '2025-12-02T03:30:39.644Z',
  'roi': None,
  'last_updated': '2026-06-04T08:05:27.983Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 243.85,
  'market_cap': 4883311548,

In [11]:
type(data)

list

In [12]:
type(response)

requests.models.Response

In [15]:
data[0]

{'id': 'bitcoin',
 'symbol': 'btc',
 'name': 'Bitcoin',
 'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
 'current_price': 63767,
 'market_cap': 1272574839213,
 'market_cap_rank': 1,
 'fully_diluted_valuation': 1272574839213,
 'total_volume': 59388208934,
 'high_24h': 67327,
 'low_24h': 61557,
 'price_change_24h': -3297.2591317158003,
 'price_change_percentage_24h': -4.91655,
 'market_cap_change_24h': -72981827510.177,
 'market_cap_change_percentage_24h': -5.42391,
 'circulating_supply': 20038434.0,
 'total_supply': 20038434.0,
 'max_supply': 21000000.0,
 'ath': 126080,
 'ath_change_percentage': -49.42314,
 'ath_date': '2025-10-06T18:57:42.558Z',
 'atl': 67.81,
 'atl_change_percentage': 93939.50483,
 'atl_date': '2013-07-06T00:00:00.000Z',
 'roi': None,
 'last_updated': '2026-06-04T08:05:30.635Z'}

In [16]:
len(data)

100

In [17]:
df = pd.DataFrame(data)

In [18]:
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,63767.000000,1272574839213,1,1272574839213,5.938821e+10,67327.000000,...,2.003843e+07,2.100000e+07,126080.000,-49.42314,2025-10-06T18:57:42.558Z,67.810000,9.393950e+04,2013-07-06T00:00:00.000Z,None,2026-06-04T08:05:30.635Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1779.850000,214167886224,2,214167886224,2.625090e+10,1886.550000,...,1.206849e+08,NaN,4946.050,-64.01473,2025-08-24T19:21:03.333Z,0.432979,4.109706e+05,2015-10-20T00:00:00.000Z,"{'times': 36.325361250625974, 'currency': 'btc...",2026-06-04T08:05:30.643Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.998961,187340958430,3,192802397763,3.404000e+11,0.999068,...,1.929966e+11,NaN,1.320,-24.49614,2018-07-24T00:00:00.000Z,0.572521,7.448933e+01,2015-03-02T00:00:00.000Z,None,2026-06-04T08:05:27.297Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,601.780000,80845491220,4,80845491220,1.968996e+09,644.830000,...,1.347843e+08,2.000000e+08,1369.990,-56.07442,2025-10-13T08:41:24.131Z,0.039818,1.511230e+06,2017-10-19T00:00:00.000Z,None,2026-06-04T08:05:30.443Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999541,75958066511,5,75960481767,2.168467e+10,1.000000,...,7.599408e+10,NaN,1.043,-4.20681,2018-11-15T00:00:00.000Z,0.877647,1.389185e+01,2023-03-11T08:02:13.981Z,None,2026-06-04T08:05:27.519Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,gho,gho,GHO,https://coin-images.coingecko.com/coins/images...,0.999323,583608508,96,583608508,7.756986e+06,0.999524,...,5.840000e+08,NaN,1.030,-2.96145,2024-02-28T17:15:58.387Z,0.917065,8.971950e+00,2023-10-24T04:41:04.568Z,None,2026-06-04T08:05:30.816Z
96,arbitrum,arb,Arbitrum,https://coin-images.coingecko.com/coins/images...,0.089424,558825963,97,893289497,8.802735e+07,0.097752,...,1.000000e+10,1.000000e+10,2.390,-96.26231,2024-01-12T12:29:59.231Z,0.087087,2.588590e+00,2026-03-29T22:50:51.753Z,None,2026-06-04T08:05:24.109Z
97,usual-usd,usd0,Usual USD,https://coin-images.coingecko.com/coins/images...,0.998411,552995272,98,552995272,4.371670e+05,0.998744,...,5.538771e+08,NaN,1.330,-24.68299,2024-07-12T08:28:59.311Z,0.962885,3.696440e+00,2025-04-10T08:30:51.088Z,None,2026-06-04T08:05:25.533Z
98,ylds,ylds,YLDS,https://coin-images.coingecko.com/coins/images...,0.999734,547377542,99,547377542,7.785596e+06,0.999868,...,5.475234e+08,NaN,1.001,-0.13499,2026-02-13T15:00:58.249Z,0.999202,5.323000e-02,2025-11-16T12:26:29.488Z,None,2026-06-04T08:05:27.085Z
99,siren-2,siren,Siren,https://coin-images.coingecko.com/coins/images...,0.735080,534997360,100,534997360,3.683211e+07,0.738264,...,7.267883e+08,1.000000e+09,3.610,-79.63219,2026-03-22T17:26:33.134Z,0.026347,2.686920e+03,2025-03-11T06:21:52.561Z,None,2026-06-04T08:05:26.737Z

# How to access data from API using RestApi

In [ ]:
import requests    # to make HTTP requests
import pandas as pd  # to convert JSON to table and save as CSV

# ──────────────────────────────────────────
# ENDPOINT — Main URL
# this is where CoinGecko keeps coins market data
# ──────────────────────────────────────────
url = "https://api.coingecko.com/api/v3/coins/markets"

# ──────────────────────────────────────────
# QUERY PARAMETERS — Special Instructions
# telling the server exactly what we want
# instead of putting them in URL we pass as dictionary
# requests library automatically adds ? and & for us
# ──────────────────────────────────────────
params = {
    "vs_currency": "usd",          # give prices in USD
    "order": "market_cap_desc",    # sort by market cap (biggest first)
    "per_page": 100,               # give 100 coins
    "page": 1,                     # first page
    "sparkline": False             # no sparkline data (keep it simple)
}

# ──────────────────────────────────────────
# REQUEST — One direct call, no session needed
# no homepage visit, no cookies, no cloudscraper
# CoinGecko is open — one shot directly
# params are automatically added to URL by requests
# ──────────────────────────────────────────
response = requests.get(url, params=params)
print(f"Status code: {response.status_code}")
# ✅ Should be 200

# ──────────────────────────────────────────
# SEE FULL URL — with params attached
# so you can see what requests built automatically
# ──────────────────────────────────────────
print(f"Full URL called: {response.url}")

# ──────────────────────────────────────────
# PARSE JSON → DataFrame
# response.json() converts raw response to Python list
# each item in list = one coin = one row
# ──────────────────────────────────────────
data = response.json()
print(f"Type of data: {type(data)}")        # should be list
print(f"Total coins received: {len(data)}") # should be 100
print(f"First coin: {data[0]}")             # see raw JSON of first coin

# ──────────────────────────────────────────
# CONVERT TO DATAFRAME → CSV
# ──────────────────────────────────────────
df = pd.DataFrame(data)
print(df.head())                      # preview first 5 rows
print(df.columns.tolist())            # see all column names

df.to_csv("crypto_market_data.csv", index=False)
print("✅ Saved to crypto_market_data.csv")

# How to access Data from all pages

In [1]:
import time
import pandas as pd
import requests

In [2]:
page = 1
all_data = []
url = "https://api.coingecko.com/api/v3/coins/markets"

In [3]:
while True:

    params = {
    "vs_currency": "usd",          # give prices in USD
    "order": "market_cap_desc",    # sort by market cap (biggest first)
    "per_page": 250,               # give 100 coins
    "page": page,                     # first page
    "sparkline": False             # no sparkline data (keep it simple)
    }

    response = requests.get(url , params=params)
    print("Response status" ,response.status_code)
    response_code = response.status_code

    if response_code == 429:
        print("We are hitting too fast")
        time.sleep(30)
        continue
    
    if response_code != 200:
        print("Errorr Error Errror")
        break

    data = response.json()
    print(f" Page{page} -> Data Received {len(data)}" )

    if len(data) == 0:
        print("Data is finished")
        break

    all_data.extend(data)
    page = page + 1
    time.sleep(2)

Response status 429
We are hitting too fast
Response status 200
 Page1 -> Data Received 250
Response status 200
 Page2 -> Data Received 250
Response status 200
 Page3 -> Data Received 250
Response status 200
 Page4 -> Data Received 250
Response status 200
 Page5 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page6 -> Data Received 250
Response status 200
 Page7 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page8 -> Data Received 250
Response status 200
 Page9 -> Data Received 250
Response status 200
 Page10 -> Data Received 250
Response status 200
 Page11 -> Data Received 250
Response status 200
 Page12 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page13 -> Data Received 250
Response status 200
 Page14 -> Data Received 250
Response status 200
 Page15 -> Data Received 250
Response status 200
 Page16 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page17 -> Data Received 250
Response status 200
 Page18 -> Data Received 250
Response status 200
 Page19 -> Data Received 250
Response status 200
 Page20 -> Data Received 250
Response status 200
 Page21 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page22 -> Data Received 250
Response status 200
 Page23 -> Data Received 250
Response status 200
 Page24 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page25 -> Data Received 250
Response status 200
 Page26 -> Data Received 250
Response status 200
 Page27 -> Data Received 250
Response status 200
 Page28 -> Data Received 250
Response status 200
 Page29 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page30 -> Data Received 250
Response status 200
 Page31 -> Data Received 250
Response status 200
 Page32 -> Data Received 250
Response status 200
 Page33 -> Data Received 250
Response status 200
 Page34 -> Data Received 250
Response status 200
 Page35 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page36 -> Data Received 250
Response status 200
 Page37 -> Data Received 250
Response status 200
 Page38 -> Data Received 250
Response status 200
 Page39 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page40 -> Data Received 250
Response status 200
 Page41 -> Data Received 250
Response status 200
 Page42 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page43 -> Data Received 250
Response status 200
 Page44 -> Data Received 250
Response status 200
 Page45 -> Data Received 250
Response status 200
 Page46 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page47 -> Data Received 250
Response status 200
 Page48 -> Data Received 250
Response status 200
 Page49 -> Data Received 250
Response status 200
 Page50 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page51 -> Data Received 250
Response status 200
 Page52 -> Data Received 250
Response status 200
 Page53 -> Data Received 250
Response status 200
 Page54 -> Data Received 250
Response status 200
 Page55 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page56 -> Data Received 250
Response status 200
 Page57 -> Data Received 250
Response status 200
 Page58 -> Data Received 250
Response status 200
 Page59 -> Data Received 250
Response status 200
 Page60 -> Data Received 250
Response status 200
 Page61 -> Data Received 250
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page62 -> Data Received 250
Response status 200
 Page63 -> Data Received 250
Response status 200
 Page64 -> Data Received 221
Response status 429
We are hitting too fast
Response status 429
We are hitting too fast
Response status 200
 Page65 -> Data Received 0
Data is finished

In [4]:
temp = all_data

In [5]:
len(temp)

15971

In [6]:
df = pd.DataFrame(temp)

In [7]:
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,63648.000000,1.275510e+12,1.0,1.275510e+12,6.775191e+10,66047.000000,...,2.003860e+07,2.100000e+07,126080.000,-49.51742,2025-10-06T18:57:42.558Z,67.810000,9.376421e+04,2013-07-06T00:00:00.000Z,None,2026-06-04T16:17:45.809Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1772.620000,2.139313e+11,2.0,2.139313e+11,2.894935e+10,1844.880000,...,1.206849e+08,NaN,4946.050,-64.16094,2025-08-24T19:21:03.333Z,0.432979,4.093004e+05,2015-10-20T00:00:00.000Z,"{'times': 36.25423775479796, 'currency': 'btc'...",2026-06-04T16:17:45.946Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.998966,1.873354e+11,3.0,1.927967e+11,2.771109e+11,0.999068,...,1.929966e+11,NaN,1.320,-24.49630,2018-07-24T00:00:00.000Z,0.572521,7.448896e+01,2015-03-02T00:00:00.000Z,None,2026-06-04T16:17:43.471Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,604.910000,8.152895e+10,4.0,8.152895e+10,2.082217e+09,628.430000,...,1.347843e+08,2.000000e+08,1369.990,-55.84560,2025-10-13T08:41:24.131Z,0.039818,1.519103e+06,2017-10-19T00:00:00.000Z,None,2026-06-04T16:17:46.256Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999640,7.594885e+10,5.0,7.605615e+10,2.474911e+10,1.000000,...,7.608370e+10,NaN,1.043,-4.19185,2018-11-15T00:00:00.000Z,0.877647,1.390964e+01,2023-03-11T08:02:13.981Z,None,2026-06-04T16:17:45.174Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15966,deepbook,adb,DeepBook,https://coin-images.coingecko.com/coins/images...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.00000,None,NaN,0.000000e+00,None,None,None
15967,wrapped-abbvie-xstock,wabbvx,Wrapped AbbVie xStock,https://coin-images.coingecko.com/coins/images...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.00000,None,NaN,0.000000e+00,None,None,None
15968,medusa-metis,metis,Medusa,https://coin-images.coingecko.com/coins/images...,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000e+10,NaN,NaN,0.00000,None,NaN,0.000000e+00,None,None,None
15969,frax-bullas,frxbullas,FRAX Bullas,https://coin-images.coingecko.com/coins/images...,NaN,NaN,NaN,NaN,NaN,NaN,...,1.776628e+13,3.333333e+14,NaN,0.00000,None,NaN,0.000000e+00,None,None,None
15970,sola-x,sax,SOLA-X,https://coin-images.coingecko.com/coins/images...,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000e+08,5.000000e+08,NaN,0.00000,None,NaN,0.000000e+00,None,None,None

In [8]:
df.to_csv("Cryptocurrency Data.csv")

# Open-meteo Weather Data

## Satara City Daily Data

In [25]:
import requests
import pandas as pd

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude":  17.68589,
    "longitude": 73.99333,
    "start_date": "2025-01-01",
    "end_date": "2025-12-31",
    "daily": [
        "weather_code",
        "temperature_2m_max",
        "temperature_2m_min",
        "apparent_temperature_max",
        "apparent_temperature_min",
        "sunrise",
        "sunset",
        "daylight_duration",
        "sunshine_duration",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "precipitation_hours",
        "wind_speed_10m_max",
        "wind_gusts_10m_max",
        "wind_direction_10m_dominant",
        "shortwave_radiation_sum",
        "et0_fao_evapotranspiration"
    ],
    "timezone": "Asia/Kolkata"
}

response = requests.get(url, params=params)
print(f"Status: {response.status_code}")

if response.status_code != 200:
    print("Error")
    print(response.text)

data = response.json()

daily_data = data["daily"]

df = pd.DataFrame(daily_data)
# print(f"Total records: {len(df)}")
# print(f"Total columns: {len(df.columns)}")
# print(df.head())

df.to_csv("Satara_Weather_Data.csv", index=False)
print("Satara_Weather_Data.csv")

Status: 200
Satara_Weather_Data.csv

In [26]:
df4 = pd.read_csv('Satara_Weather_Data.csv')

In [27]:
df4

,time,weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,daylight_duration,sunshine_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,shortwave_radiation_sum,et0_fao_evapotranspiration
0,2025-01-01,2,28.2,16.5,28.8,17.3,2025-01-01T07:04,2025-01-01T18:10,39934.14,37555.66,0.0,0.0,0.0,0.0,13.1,31.0,76,18.45,3.77
1,2025-01-02,3,28.8,15.1,28.2,16.3,2025-01-02T07:05,2025-01-02T18:11,39949.70,36737.99,0.0,0.0,0.0,0.0,13.1,30.2,67,18.67,3.97
2,2025-01-03,3,27.9,14.6,25.6,14.3,2025-01-03T07:05,2025-01-03T18:11,39966.49,38047.56,0.0,0.0,0.0,0.0,13.5,32.0,81,19.27,4.08
3,2025-01-04,3,27.9,14.0,27.0,13.5,2025-01-04T07:05,2025-01-04T18:12,39984.52,38292.83,0.0,0.0,0.0,0.0,11.4,28.8,121,19.28,3.74
4,2025-01-05,0,27.5,14.4,27.1,13.8,2025-01-05T07:06,2025-01-05T18:12,40003.74,38272.22,0.0,0.0,0.0,0.0,8.4,23.4,139,19.05,3.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2025-12-27,0,26.0,12.6,25.4,11.6,2025-12-27T07:02,2025-12-27T18:07,39873.38,37484.59,0.0,0.0,0.0,0.0,10.4,25.6,113,18.97,3.59
361,2025-12-28,0,26.0,12.2,25.6,11.1,2025-12-28T07:03,2025-12-28T18:08,39881.73,37479.40,0.0,0.0,0.0,0.0,12.0,28.8,120,18.92,3.58
362,2025-12-29,1,26.1,12.6,25.6,12.0,2025-12-29T07:03,2025-12-29T18:08,39891.41,37739.89,0.0,0.0,0.0,0.0,10.0,25.6,118,18.93,3.51
363,2025-12-30,2,27.2,12.9,27.1,12.5,2025-12-30T07:04,2025-12-30T18:09,39902.43,37598.77,0.0,0.0,0.0,0.0,6.9,21.2,240,18.94,3.64
364,2025-12-31,2,27.4,13.1,27.4,13.2,2025-12-31T07:04,2025-12-31T18:09,39914.77,37846.78,0.0,0.0,0.0,0.0,14.4,31.3,266,18.90,3.85

## Uran-Ishwarpur Hourly data for 2020-2025

In [ ]:
import requests
import pandas as pd

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
   "latitude": 17.6805,
    "longitude": 74.0183,
    "start_date": "2020-01-01",
    "end_date": "2025-12-31",
    "hourly": [
    "temperature_2m",
    "relative_humidity_2m",
    "dew_point_2m",
    "apparent_temperature",
    "precipitation",
    "rain",
    "snowfall",
    "snow_depth",
    "weather_code",
    "pressure_msl",
    "surface_pressure",
    "cloud_cover",
    "cloud_cover_low",
    "cloud_cover_mid",
    "cloud_cover_high",
    "wind_speed_10m",
    "wind_speed_100m",
    "wind_direction_10m",
    "wind_direction_100m",
    "wind_gusts_10m",
    "soil_temperature_0_to_7cm",
    "soil_temperature_7_to_28cm",
    "soil_temperature_28_to_100cm",
    "soil_temperature_100_to_255cm",
    "soil_moisture_0_to_7cm",
    "soil_moisture_7_to_28cm",
    "soil_moisture_28_to_100cm",
    "soil_moisture_100_to_255cm",
    "shortwave_radiation",
    "vapour_pressure_deficit",
    "et0_fao_evapotranspiration"
],
    "timezone": "Asia/Kolkata"
}

response = requests.get(url, params=params)
print(f"Status: {response.status_code}")

if response.status_code != 200:
    print("Error")
    print(response.text)

data = response.json()

daily_data = data["hourly"]

df = pd.DataFrame(daily_data)
# print(f"Total records: {len(df)}")
# print(f"Total columns: {len(df.columns)}")
# print(df.head())

df.to_csv("Ishwarpur_Hourly_Weather_Data.csv", index=False)
print("Done")

Status: 200
Done

In [13]:
df

,time,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,snow_depth,weather_code,...,soil_temperature_7_to_28cm,soil_temperature_28_to_100cm,soil_temperature_100_to_255cm,soil_moisture_0_to_7cm,soil_moisture_7_to_28cm,soil_moisture_28_to_100cm,soil_moisture_100_to_255cm,shortwave_radiation,vapour_pressure_deficit,et0_fao_evapotranspiration
0,2020-01-01T00:00,18.0,76,13.8,18.3,0.0,0.0,0.0,0.0,0,...,24.9,25.0,25.4,0.193,0.324,0.390,0.474,0.0,0.49,0.01
1,2020-01-01T01:00,17.5,79,13.8,17.8,0.0,0.0,0.0,0.0,0,...,24.7,25.0,25.4,0.193,0.324,0.390,0.474,0.0,0.42,0.00
2,2020-01-01T02:00,16.9,82,13.8,17.2,0.0,0.0,0.0,0.0,0,...,24.5,25.0,25.4,0.193,0.324,0.390,0.474,0.0,0.34,0.00
3,2020-01-01T03:00,16.4,84,13.7,16.7,0.0,0.0,0.0,0.0,0,...,24.3,25.0,25.4,0.193,0.324,0.390,0.474,0.0,0.30,0.00
4,2020-01-01T04:00,16.0,86,13.6,16.3,0.0,0.0,0.0,0.0,0,...,24.1,25.0,25.4,0.194,0.324,0.390,0.474,0.0,0.26,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52603,2025-12-31T19:00,21.9,46,9.9,20.1,0.0,0.0,0.0,0.0,2,...,22.4,22.5,24.1,0.238,0.287,0.415,0.445,0.0,1.41,0.08
52604,2025-12-31T20:00,20.6,52,10.5,19.2,0.0,0.0,0.0,0.0,2,...,22.5,22.5,24.1,0.238,0.287,0.415,0.445,0.0,1.16,0.06
52605,2025-12-31T21:00,19.6,57,10.8,18.5,0.0,0.0,0.0,0.0,2,...,22.5,22.5,24.1,0.238,0.287,0.415,0.445,0.0,0.99,0.05
52606,2025-12-31T22:00,18.6,62,11.1,17.5,0.0,0.0,0.0,0.0,2,...,22.5,22.5,24.1,0.238,0.287,0.415,0.445,0.0,0.82,0.04
52607,2025-12-31T23:00,18.0,66,11.6,17.0,0.0,0.0,0.0,0.0,3,...,22.4,22.5,24.1,0.238,0.287,0.414,0.445,0.0,0.70,0.03